var React = require('react'),
  ReactDOM = require('react-dom'),
  Feeds = require('./components/Feeds'),
  ContextMenu = require('./components/ContextMenu'),
  Modal = require('./components/bootstrap/Modal'),
  log = require('./log');

var ui = {
  /*
   * Events generated by UI
   */
  eventHandlers: {
    // Select feed to see it's items
    onSelectFeed: [],
  },

  /*
   * Attach a listener to one of UI events
   */
  registerHandler: function(key, fn) {
    ui.eventHandlers[key].push(fn);
  },

  /*
   * Private
   *
   * UI events emitter
   */
  getHandler: function(key) {
    return function(data) {
      for(let h of ui.eventHandlers[key]) {
        h(data);
      }
    };
  },

  renderFeeds: function(data) {
    ReactDOM.render(
      // jshint ignore:start
      <Feeds onFeedContextMenu={ui.showFeedContextMenu}
      onSelectFeed={ui.getHandler("onSelectFeed")} data={data} />,
      // jshint ignore:end
      document.getElementById("feeds")
    );
  },

  showContextMenu: function(options, callback) {
    ReactDOM.render(
      // jshint ignore:start
      <ContextMenu top={ui.mouseY} left={ui.mouseX}
      onSelectOption={callback} show={true} options={options} />,
      // jshint ignore:end
      document.getElementById("context-menu")
    );
  },

  showFeedContextMenu: function(feed) {
    const options = {
      editFeed: "Edit Feed"
    };

    ui.showContextMenu(options, function(option) {
      switch(option) {
        case "editFeed":
          console.log("Edit feed!", feed);
          break;
      }
    });
  },

  mouseY: 0,
  mouseX: 0
};

window.document.addEventListener('mousemove', (e) => {
  ui.mouseY = e.clientY;
  ui.mouseX = e.clientX;
});

module.exports = ui;
