var React = require('react'),
    ReactDOM = require('react-dom'),
		Feeds = require('./components/Feeds'),
		ContextMenu = require('./components/ContextMenu'),
    log = require('./log');

var ui = {
	/*
	 * Events generated by UI
	 */
	eventHandlers: {
		onSelectFeed: []
	},

	/*
	 * Attach a listener to one of UI events
	 */
	registerHandler: function(key, fn) {
		ui.eventHandlers[key].push(fn);
	},

	/*
	 * Private
	 *
	 * UI events emitter
	 */
	getHandler: function(key) {
		return function(data) {
			for(let h of ui.eventHandlers[key]) {
				h(data);
			}
		};
	},

	renderFeeds: function(data) {
		ReactDOM.render(
			// jshint ignore:start
			<Feeds onSelectFeed={ui.getHandler("onSelectFeed")} data={data} />,
			// jshint ignore:end
			document.getElementById("feeds")
		);
	},

	renderContextMenu: function(show, options, callback) {
		ReactDOM.render(
			// jshint ignore:start
			<ContextMenu top={ui.mouseY} left={ui.mouseX}
					onSelectOption={callback} show={show} options={options} />,
			// jshint ignore:end
			document.getElementById("context-menu")
		);
	},

	mouseY: 0,
	mouseX: 0
};

window.document.addEventListener('mousemove', (e) => {
	ui.mouseY = e.clientY;
	ui.mouseX = e.clientX;
});

module.exports = ui;
