require 'rake/clean'
CLEAN << FileList.glob('static/assets/**/*.{js,css,map}')
CLEAN << FileList.glob('bindata*.go')
CLEAN << FileList.glob('web')

WEBPACK = './node_modules/.bin/webpack'

production = false

file 'static/assets/css/app.css' => 'src/scss/app.scss' do |t|
  sh "sassc -I src/scss #{t.prerequisites.join(' ')} #{t.name}"
end

# Assuming that sourcea and output files are specified in webpack.config.js
file 'static/assets/js/bundle.js' => 'src/index.js' do
  sh 'yarn install'

  if production
    sh WEBPACK, '-p'
  else
    sh WEBPACK
  end
end

file 'static/assets/js/ressweb.js' => FileList.glob('ressweb/**/*.go') do |t|
  sh 'go get -v github.com/gopherjs/gopherjs'
  Dir.chdir 'ressweb' do
    sh 'go get -v'
  end
  sh "gopherjs build -o #{t.name} "\
      "github.com/mluts/ress/ui/web/ressweb/ajax "\
      "github.com/mluts/ress/ui/web/ressweb/console "\
      "github.com/mluts/ress/ui/web/ressweb"
end

file 'bindata_assetfs.go' => %w(static/assets/css/app.css
                                static/assets/js/bundle.js
                                static/assets/js/ressweb.js) do |t|
  sh 'go get -v github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs'
  sh "go-bindata-assetfs #{production ? '' : '-dev'} -prefix `realpath .` `find static -type d`"
  FileUtils.mv 'bindata_assetfs.go', t.name unless t.name == 'bindata_assetfs.go'
end

file 'web' => 'bindata_assetfs.go' do |t|
  sh "go build -o #{t.name}"
end

task build: 'web'

task production: :clean do
  puts 'Building for production'
  production = true
end

task default: :build
